In [8]:
from datetime import datetime

# key parameters
MODEL = "openai/gpt-5-mini"#"google/gemini-3-flash-preview"
IMAGE_SET = "sample.csv"
DATA_SPLIT = "all"
SAMPLE_LIMIT = 90
FEATURES = ["key_flower_type", "key_plant_type", "key_leaf_type"]
PROMPT_SET = "stepwise-v1.json"
RUN_ID = "run-gpt-5-mini"

# helper parameters
TEMPERATURE = 0.0
MAX_TOKENS = 200
MODE = "command"
WORKERS = 1
TIMEOUT = 120
TRIAL_ID = f"notebook-{datetime.now().strftime('%Y%m%d-%H%M%S')}"
OUT_FILE = ""  # blank means trials/artifacts/{TRIAL_ID}.csv

In [9]:
from pathlib import Path
import sys

NOTEBOOK_DIR = Path.cwd() if (Path.cwd() / "utilities.py").exists() else Path.cwd() / "notebooks"
if str(NOTEBOOK_DIR) not in sys.path:
    sys.path.insert(0, str(NOTEBOOK_DIR))

from utilities import run_stepwise_notebook_trial


result = run_stepwise_notebook_trial(
    model=MODEL,
    mode=MODE,
    image_set=IMAGE_SET,
    data_split=DATA_SPLIT,
    sample_limit=SAMPLE_LIMIT,
    features=FEATURES,
    prompt_set=PROMPT_SET,
    temperature=TEMPERATURE,
    max_tokens=MAX_TOKENS,
    workers=WORKERS,
    timeout=TIMEOUT,
    run_id=RUN_ID,
    trial_id=TRIAL_ID,
    out_file=OUT_FILE,
)

Running JM stepwise trial
  trial id: notebook-20260701-085321
  image set: sample.csv
  data split: all
  prompt set: stepwise-v1
  run id: run-gpt-5-mini
  model: openai/gpt-5-mini
  sample limit: 90
  features: key_flower_type,key_plant_type,key_leaf_type
  temperature: 0.0
  max tokens: 200
  workers: 1
  timeout: 120s per model call
  output: trials/artifacts/notebook-20260701-085321.csv
  metadata: trials/artifacts/notebook-20260701-085321.metadata.json

=== openai/gpt-5-mini ===
image set: sample.csv (/Users/lindseyma/Documents/GitHub/arborphy/newcomb_wildflower_guide/experiment_repro/output/sample.csv)
sample rows: 90
sample limit: 90
features: key_flower_type, key_plant_type, key_leaf_type
prompt set: stepwise-v1
run id: run-gpt-5-mini
workers: 1
output: /Users/lindseyma/Documents/GitHub/arborphy/trials/artifacts/notebook-20260701-085321.csv
  obs=36899280 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=36899280 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=36899280 key_leaf_type P1=NO P2=INCONCLUSIVE [✗]
  obs=51163540 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=51163540 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=51163540 key_leaf_type P1=YES P2=Leaves Entire [✓]
  obs=14859795 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=14859795 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=14859795 key_leaf_type P1=YES P2=Leaves Entire [✓]
  obs=55121380 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=55121380 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=55121380 key_leaf_type P1=NO P2=INCONCLUSIVE [✗]
  obs=3900142 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=3900142 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=3900142 key_leaf_type P1=YES P2=INCONCLUSIVE [✗]
  obs=180909839 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=180909839 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=180909839 key_leaf_type P1=NO P2=INCONCLUSIVE [✗]
  obs=177208695 key_flower_type P1=YES P2=Asters (Aster) [✗]
  obs=177208695 key_plant_type P1=YES P2=Wildflowers - Alternate Leaves [✓]
  obs=177208695 key_leaf_type P1=YES P2=Leaves Toothed or Lobed [✓]
  obs=240602873 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=240602873 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=240602873 key_leaf_type P1=NO P2=INCONCLUSIVE [✗]
  obs=55587991 key_flower_type P1=YES P2=Asters (Aster) [✗]
  obs=55587991 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=55587991 key_leaf_type P1=YES P2=Leaves Toothed or Lobed [✓]
  obs=71079777 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=71079777 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=71079777 key_leaf_type P1=YES P2=Leaves Divided [✓]
  obs=164528211 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=164528211 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=164528211 key_leaf_type P1=YES P2=Leaves Toothed or Lobed [✗]
  obs=154911531 key_flower_type P1=NO P2=INCONCLUSIVE [✗]
  obs=154911531 key_plant_type P1=NO P2=INCONCLUSIVE [✗]
  obs=154911531 key_leaf_type P1=YES P2=Leaves Toothed or Lobed [✗]

Done. Raw results -> /Users/lindseyma/Documents/GitHub/arborphy/trials/artifacts/notebook-20260701-085321.csv

### Trial saved to `trials/artifacts/notebook-20260701-085321.csv`

,trial_id,command,image_set,data_split,prompt_set,run_id,model,sample_limit,features,temperature,max_tokens,mode,output_file,python,package_manager
0,notebook-20260701-085321,uv run python scripts/run_stepwise_trial.py --...,sample.csv,all,stepwise-v1,run-gpt-5-mini,openai/gpt-5-mini,90,"[key_flower_type, key_plant_type, key_leaf_type]",0.0,200,command,trials/artifacts/notebook-20260701-085321.csv,3.12.10,uv

### Whole-Experiment Dashboard

                     metric          value
0             feature_tasks             36
1       unique_observations             12
2                    trials              1
3                    models              1
4                  features              3
5             features_seen  11/36 (30.6%)
6                 committed  10/36 (27.8%)
7                   correct   6/36 (16.7%)
8                     wrong   4/36 (11.1%)
9              inconclusive  26/36 (72.2%)
10  accuracy_when_committed   6/10 (60.0%)

### Per-Feature / Model Summary (Compact)

,trial_id,run_id,model,prompt_set,feature,n,observations,seen,committed,correct,wrong,inconclusive,accuracy_when_committed
0,notebook-20260701-085321,run-gpt-5-mini,openai/gpt-5-mini,stepwise-v1,key_flower_type,12,12,2/12 (16.7%),2/12 (16.7%),0/12 (0.0%),2/12 (16.7%),10/12 (83.3%),0/2 (0.0%)
1,notebook-20260701-085321,run-gpt-5-mini,openai/gpt-5-mini,stepwise-v1,key_leaf_type,12,12,8/12 (66.7%),7/12 (58.3%),5/12 (41.7%),2/12 (16.7%),5/12 (41.7%),5/7 (71.4%)
2,notebook-20260701-085321,run-gpt-5-mini,openai/gpt-5-mini,stepwise-v1,key_plant_type,12,12,1/12 (8.3%),1/12 (8.3%),1/12 (8.3%),0/12 (0.0%),11/12 (91.7%),1/1 (100.0%)

### Outcome by True Value

,model,feature,true_value,n,correct,wrong,inconclusive,most_common_wrong_prediction
0,openai/gpt-5-mini,key_flower_type,5 Regular Parts,6,0/6 (0.0%),0/6 (0.0%),6/6 (100.0%),
1,openai/gpt-5-mini,key_flower_type,6 Regular Parts,3,0/3 (0.0%),0/3 (0.0%),3/3 (100.0%),
2,openai/gpt-5-mini,key_flower_type,7 or More Regular Parts,3,0/3 (0.0%),2/3 (66.7%),1/3 (33.3%),Asters (Aster)
3,openai/gpt-5-mini,key_leaf_type,Leaves Divided,3,1/3 (33.3%),2/3 (66.7%),0/3 (0.0%),Leaves Toothed or Lobed
4,openai/gpt-5-mini,key_leaf_type,Leaves Entire,6,2/6 (33.3%),0/6 (0.0%),4/6 (66.7%),
5,openai/gpt-5-mini,key_leaf_type,Leaves Toothed or Lobed,3,2/3 (66.7%),0/3 (0.0%),1/3 (33.3%),
6,openai/gpt-5-mini,key_plant_type,Wildflowers - Alternate Leaves,9,1/9 (11.1%),0/9 (0.0%),8/9 (88.9%),
7,openai/gpt-5-mini,key_plant_type,Wildflowers - Basal Leaves Only,3,0/3 (0.0%),0/3 (0.0%),3/3 (100.0%),

### Outcome Pairs: True Value x Predicted Value

,model,feature,true_value,predicted_value,outcome,count
0,openai/gpt-5-mini,key_flower_type,5 Regular Parts,INCONCLUSIVE,INCONCLUSIVE,6
1,openai/gpt-5-mini,key_flower_type,6 Regular Parts,INCONCLUSIVE,INCONCLUSIVE,3
2,openai/gpt-5-mini,key_flower_type,7 or More Regular Parts,Asters (Aster),WRONG,2
3,openai/gpt-5-mini,key_flower_type,7 or More Regular Parts,INCONCLUSIVE,INCONCLUSIVE,1
4,openai/gpt-5-mini,key_leaf_type,Leaves Divided,Leaves Divided,CORRECT,1
5,openai/gpt-5-mini,key_leaf_type,Leaves Divided,Leaves Toothed or Lobed,WRONG,2
6,openai/gpt-5-mini,key_leaf_type,Leaves Entire,INCONCLUSIVE,INCONCLUSIVE,4
7,openai/gpt-5-mini,key_leaf_type,Leaves Entire,Leaves Entire,CORRECT,2
8,openai/gpt-5-mini,key_leaf_type,Leaves Toothed or Lobed,INCONCLUSIVE,INCONCLUSIVE,1
9,openai/gpt-5-mini,key_leaf_type,Leaves Toothed or Lobed,Leaves Toothed or Lobed,CORRECT,2
10,openai/gpt-5-mini,key_plant_type,Wildflowers - Alternate Leaves,INCONCLUSIVE,INCONCLUSIVE,8
11,openai/gpt-5-mini,key_plant_type,Wildflowers - Alternate Leaves,Wildflowers - Alternate Leaves,CORRECT,1
12,openai/gpt-5-mini,key_plant_type,Wildflowers - Basal Leaves Only,INCONCLUSIVE,INCONCLUSIVE,3

### Per-Trial Rows (First 50)

,observation_id,model,prompt_set,feature,true_value,p1_parsed,p2_parsed,outcome
0,36899280,openai/gpt-5-mini,stepwise-v1,key_flower_type,6 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
1,36899280,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
2,36899280,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Entire,NO,INCONCLUSIVE,INCONCLUSIVE
3,51163540,openai/gpt-5-mini,stepwise-v1,key_flower_type,6 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
4,51163540,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
5,51163540,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Entire,YES,Leaves Entire,CORRECT
6,14859795,openai/gpt-5-mini,stepwise-v1,key_flower_type,6 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
7,14859795,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
8,14859795,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Entire,YES,Leaves Entire,CORRECT
9,55121380,openai/gpt-5-mini,stepwise-v1,key_flower_type,5 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
10,55121380,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Basal Leaves Only,NO,INCONCLUSIVE,INCONCLUSIVE
11,55121380,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Entire,NO,INCONCLUSIVE,INCONCLUSIVE
12,3900142,openai/gpt-5-mini,stepwise-v1,key_flower_type,5 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
13,3900142,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Basal Leaves Only,NO,INCONCLUSIVE,INCONCLUSIVE
14,3900142,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Entire,YES,INCONCLUSIVE,INCONCLUSIVE
15,180909839,openai/gpt-5-mini,stepwise-v1,key_flower_type,5 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
16,180909839,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Basal Leaves Only,NO,INCONCLUSIVE,INCONCLUSIVE
17,180909839,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Entire,NO,INCONCLUSIVE,INCONCLUSIVE
18,177208695,openai/gpt-5-mini,stepwise-v1,key_flower_type,7 or More Regular Parts,YES,Asters (Aster),WRONG
19,177208695,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,YES,Wildflowers - Alternate Leaves,CORRECT
20,177208695,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Toothed or Lobed,YES,Leaves Toothed or Lobed,CORRECT
21,240602873,openai/gpt-5-mini,stepwise-v1,key_flower_type,7 or More Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
22,240602873,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
23,240602873,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Toothed or Lobed,NO,INCONCLUSIVE,INCONCLUSIVE
24,55587991,openai/gpt-5-mini,stepwise-v1,key_flower_type,7 or More Regular Parts,YES,Asters (Aster),WRONG
25,55587991,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
26,55587991,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Toothed or Lobed,YES,Leaves Toothed or Lobed,CORRECT
27,71079777,openai/gpt-5-mini,stepwise-v1,key_flower_type,5 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
28,71079777,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
29,71079777,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Divided,YES,Leaves Divided,CORRECT
30,164528211,openai/gpt-5-mini,stepwise-v1,key_flower_type,5 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
31,164528211,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
32,164528211,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Divided,YES,Leaves Toothed or Lobed,WRONG
33,154911531,openai/gpt-5-mini,stepwise-v1,key_flower_type,5 Regular Parts,NO,INCONCLUSIVE,INCONCLUSIVE
34,154911531,openai/gpt-5-mini,stepwise-v1,key_plant_type,Wildflowers - Alternate Leaves,NO,INCONCLUSIVE,INCONCLUSIVE
35,154911531,openai/gpt-5-mini,stepwise-v1,key_leaf_type,Leaves Divided,YES,Leaves Toothed or Lobed,WRONG

### Metric Definitions

,metric,numerator,denominator,csv_formula,useful_signal
0,feature_count,count(rows),,one row = one observation_id x feature task,Experiment size and denominator; not a perform...
1,features_seen,count(p1_parsed == 'YES'),feature_count,p1_parsed,Visibility-gate or model-willingness signal; n...
2,commitment_rate,"count(outcome in {'CORRECT', 'WRONG'})",feature_count,"p2_parsed not in {'', 'INCONCLUSIVE'}",How often the model gives a concrete class ins...
3,correct_count,count(p2_parsed == true_value),,"p2_parsed, true_value",Direct count of solved tasks.
4,wrong_count,"count(p2_parsed not in {'', 'INCONCLUSIVE'} an...",,"p2_parsed, true_value",Direct count of concrete but wrong answers.
5,inconclusive_count,count(p2_parsed == 'INCONCLUSIVE'),,p2_parsed,Direct count of abstentions or skipped P2 cases.
6,correct_rate,correct_count,feature_count,outcome == 'CORRECT',Best single end-to-end success rate when INCON...
7,wrong_rate,wrong_count,feature_count,outcome == 'WRONG',Risk signal: how often the model gives a concr...
8,inconclusive_rate,inconclusive_count,feature_count,outcome == 'INCONCLUSIVE',Uncertainty or abstention signal; pair with co...
9,committed_accuracy,correct_count,correct_count + wrong_count,outcome == 'CORRECT' among concrete outcomes,Quality score among concrete answers; pair wit...
10,most_common_wrong_prediction,mode(predicted_value where outcome == 'WRONG'),,"predicted_value, outcome",Shows the most common concrete wrong predictio...